/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as DemoPanel01RouteImport } from './routes/demo/panel-01'
import { Route as DemoPanel02RouteImport } from './routes/demo/panel-02'
import { Route as DemoPanel03RouteImport } from './routes/demo/panel-03'
import { Route as DemoPanel04RouteImport } from './routes/demo/panel-04'
import { Route as DemoPanel05RouteImport } from './routes/demo/panel-05'
import { Route as DemoPanel06RouteImport } from './routes/demo/panel-06'
import { Route as DemoPanel07RouteImport } from './routes/demo/panel-07'
import { Route as DemoPanel08RouteImport } from './routes/demo/panel-08'
import { Route as DemoPanel09RouteImport } from './routes/demo/panel-09'
import { Route as DemoPanel10RouteImport } from './routes/demo/panel-10'
import { Route as DemoPanel11RouteImport } from './routes/demo/panel-11'
import { Route as DemoPanel12RouteImport } from './routes/demo/panel-12'
import { Route as DemoPanel13RouteImport } from './routes/demo/panel-13'
import { Route as DemoPanel14RouteImport } from './routes/demo/panel-14'
import { Route as DemoPanel15RouteImport } from './routes/demo/panel-15'
import { Route as DemoPanel16RouteImport } from './routes/demo/panel-16'
import { Route as DemoPanel17RouteImport } from './routes/demo/panel-17'
import { Route as DemoPanel18RouteImport } from './routes/demo/panel-18'
import { Route as DemoPanel19RouteImport } from './routes/demo/panel-19'
import { Route as DemoPanel20RouteImport } from './routes/demo/panel-20'
import { Route as DemoPanel21RouteImport } from './routes/demo/panel-21'
import { Route as DemoPanel22RouteImport } from './routes/demo/panel-22'
import { Route as DemoPanel23RouteImport } from './routes/demo/panel-23'
import { Route as DemoPanel24RouteImport } from './routes/demo/panel-24'
import { Route as DemoPanel25RouteImport } from './routes/demo/panel-25'
import { Route as DemoPanel26RouteImport } from './routes/demo/panel-26'
import { Route as DemoPanel27RouteImport } from './routes/demo/panel-27'
import { Route as DemoPanel28RouteImport } from './routes/demo/panel-28'
import { Route as DemoPanel29RouteImport } from './routes/demo/panel-29'
import { Route as DemoPanel30RouteImport } from './routes/demo/panel-30'
import { Route as DemoPanel31RouteImport } from './routes/demo/panel-31'
import { Route as DemoPanel32RouteImport } from './routes/demo/panel-32'
import { Route as DemoPanel33RouteImport } from './routes/demo/panel-33'
import { Route as DemoPanel34RouteImport } from './routes/demo/panel-34'
import { Route as DemoPanel35RouteImport } from './routes/demo/panel-35'
import { Route as DemoPanel36RouteImport } from './routes/demo/panel-36'
import { Route as DemoPanel37RouteImport } from './routes/demo/panel-37'
import { Route as DemoPanel38RouteImport } from './routes/demo/panel-38'
import { Route as DemoPanel39RouteImport } from './routes/demo/panel-39'
import { Route as DemoPanel40RouteImport } from './routes/demo/panel-40'
import { Route as DemoPanel41RouteImport } from './routes/demo/panel-41'
import { Route as DemoPanel42RouteImport } from './routes/demo/panel-42'
import { Route as DemoPanel43RouteImport } from './routes/demo/panel-43'
import { Route as DemoPanel44RouteImport } from './routes/demo/panel-44'
import { Route as DemoPanel45RouteImport } from './routes/demo/panel-45'
import { Route as DemoPanel46RouteImport } from './routes/demo/panel-46'
import { Route as DemoPanel47RouteImport } from './routes/demo/panel-47'
import { Route as DemoPanel48RouteImport } from './routes/demo/panel-48'
import { Route as DemoPanel49RouteImport } from './routes/demo/panel-49'
import { Route as DemoPanel50RouteImport } from './routes/demo/panel-50'
import { Route as DemoPanel51RouteImport } from './routes/demo/panel-51'
import { Route as DemoPanel52RouteImport } from './routes/demo/panel-52'
import { Route as DemoPanel53RouteImport } from './routes/demo/panel-53'
import { Route as DemoPanel54RouteImport } from './routes/demo/panel-54'
import { Route as DemoPanel55RouteImport } from './routes/demo/panel-55'
import { Route as DemoPanel56RouteImport } from './routes/demo/panel-56'
import { Route as DemoPanel57RouteImport } from './routes/demo/panel-57'
import { Route as DemoPanel58RouteImport } from './routes/demo/panel-58'
import { Route as DemoPanel59RouteImport } from './routes/demo/panel-59'
import { Route as DemoPanel60RouteImport } from './routes/demo/panel-60'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPanel01Route = DemoPanel01RouteImport.update({
  id: '/demo/panel-01',
  path: '/demo/panel-01',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPanel02Route = DemoPanel02RouteImport.update({
  id: '/demo/panel-02',
  path: '/demo/panel-02',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPanel03Route = DemoPanel03RouteImport.update({
  id: '/demo/panel-03',
  path: '/demo/panel-03',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPanel04Route = DemoPanel04RouteImport.update({
  id: '/demo/panel-04',
  path: '/demo/panel-04',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPanel05Route = DemoPanel05RouteImport.update({
  id: '/demo/panel-05',
  path: '/demo/panel-05',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPanel06Route = DemoPanel06RouteImport.update({
  id: '/demo/panel-06',
  path: '/demo/panel-06',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPanel07Route = DemoPanel07RouteImport.update({
  id: '/demo/panel-07',
  path: '/demo/panel-07',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPanel08Route = DemoPanel08RouteImport.update({
  id: '/demo/panel-08',
  path: '/demo/panel-08',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPanel09Route = DemoPanel09RouteImport.update({
  id: '/demo/panel-09',
  path: '/demo/panel-09',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPanel10Route = DemoPanel10RouteImport.update({
  id: '/demo/panel-10',
  path: '/demo/panel-10',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPanel11Route = DemoPanel11RouteImport.update({
  id: '/demo/panel-11',
  path: '/demo/panel-11',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPanel12Route = DemoPanel12RouteImport.update({
  id: '/demo/panel-12',
  path: '/demo/panel-12',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPanel13Route = DemoPanel13RouteImport.update({
  id: '/demo/panel-13',
  path: '/demo/panel-13',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPanel14Route = DemoPanel14RouteImport.update({
  id: '/demo/panel-14',
  path: '/demo/panel-14',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPanel15Route = DemoPanel15RouteImport.update({
  id: '/demo/panel-15',
  path: '/demo/panel-15',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPanel16Route = DemoPanel16RouteImport.update({
  id: '/demo/panel-16',
  path: '/demo/panel-16',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPanel17Route = DemoPanel17RouteImport.update({
  id: '/demo/panel-17',
  path: '/demo/panel-17',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPanel18Route = DemoPanel18RouteImport.update({
  id: '/demo/panel-18',
  path: '/demo/panel-18',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPanel19Route = DemoPanel19RouteImport.update({
  id: '/demo/panel-19',
  path: '/demo/panel-19',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPanel20Route = DemoPanel20RouteImport.update({
  id: '/demo/panel-20',
  path: '/demo/panel-20',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPanel21Route = DemoPanel21RouteImport.update({
  id: '/demo/panel-21',
  path: '/demo/panel-21',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPanel22Route = DemoPanel22RouteImport.update({
  id: '/demo/panel-22',
  path: '/demo/panel-22',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPanel23Route = DemoPanel23RouteImport.update({
  id: '/demo/panel-23',
  path: '/demo/panel-23',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPanel24Route = DemoPanel24RouteImport.update({
  id: '/demo/panel-24',
  path: '/demo/panel-24',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPanel25Route = DemoPanel25RouteImport.update({
  id: '/demo/panel-25',
  path: '/demo/panel-25',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPanel26Route = DemoPanel26RouteImport.update({
  id: '/demo/panel-26',
  path: '/demo/panel-26',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPanel27Route = DemoPanel27RouteImport.update({
  id: '/demo/panel-27',
  path: '/demo/panel-27',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPanel28Route = DemoPanel28RouteImport.update({
  id: '/demo/panel-28',
  path: '/demo/panel-28',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPanel29Route = DemoPanel29RouteImport.update({
  id: '/demo/panel-29',
  path: '/demo/panel-29',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPanel30Route = DemoPanel30RouteImport.update({
  id: '/demo/panel-30',
  path: '/demo/panel-30',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPanel31Route = DemoPanel31RouteImport.update({
  id: '/demo/panel-31',
  path: '/demo/panel-31',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPanel32Route = DemoPanel32RouteImport.update({
  id: '/demo/panel-32',
  path: '/demo/panel-32',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPanel33Route = DemoPanel33RouteImport.update({
  id: '/demo/panel-33',
  path: '/demo/panel-33',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPanel34Route = DemoPanel34RouteImport.update({
  id: '/demo/panel-34',
  path: '/demo/panel-34',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPanel35Route = DemoPanel35RouteImport.update({
  id: '/demo/panel-35',
  path: '/demo/panel-35',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPanel36Route = DemoPanel36RouteImport.update({
  id: '/demo/panel-36',
  path: '/demo/panel-36',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPanel37Route = DemoPanel37RouteImport.update({
  id: '/demo/panel-37',
  path: '/demo/panel-37',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPanel38Route = DemoPanel38RouteImport.update({
  id: '/demo/panel-38',
  path: '/demo/panel-38',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPanel39Route = DemoPanel39RouteImport.update({
  id: '/demo/panel-39',
  path: '/demo/panel-39',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPanel40Route = DemoPanel40RouteImport.update({
  id: '/demo/panel-40',
  path: '/demo/panel-40',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPanel41Route = DemoPanel41RouteImport.update({
  id: '/demo/panel-41',
  path: '/demo/panel-41',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPanel42Route = DemoPanel42RouteImport.update({
  id: '/demo/panel-42',
  path: '/demo/panel-42',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPanel43Route = DemoPanel43RouteImport.update({
  id: '/demo/panel-43',
  path: '/demo/panel-43',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPanel44Route = DemoPanel44RouteImport.update({
  id: '/demo/panel-44',
  path: '/demo/panel-44',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPanel45Route = DemoPanel45RouteImport.update({
  id: '/demo/panel-45',
  path: '/demo/panel-45',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPanel46Route = DemoPanel46RouteImport.update({
  id: '/demo/panel-46',
  path: '/demo/panel-46',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPanel47Route = DemoPanel47RouteImport.update({
  id: '/demo/panel-47',
  path: '/demo/panel-47',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPanel48Route = DemoPanel48RouteImport.update({
  id: '/demo/panel-48',
  path: '/demo/panel-48',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPanel49Route = DemoPanel49RouteImport.update({
  id: '/demo/panel-49',
  path: '/demo/panel-49',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPanel50Route = DemoPanel50RouteImport.update({
  id: '/demo/panel-50',
  path: '/demo/panel-50',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPanel51Route = DemoPanel51RouteImport.update({
  id: '/demo/panel-51',
  path: '/demo/panel-51',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPanel52Route = DemoPanel52RouteImport.update({
  id: '/demo/panel-52',
  path: '/demo/panel-52',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPanel53Route = DemoPanel53RouteImport.update({
  id: '/demo/panel-53',
  path: '/demo/panel-53',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPanel54Route = DemoPanel54RouteImport.update({
  id: '/demo/panel-54',
  path: '/demo/panel-54',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPanel55Route = DemoPanel55RouteImport.update({
  id: '/demo/panel-55',
  path: '/demo/panel-55',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPanel56Route = DemoPanel56RouteImport.update({
  id: '/demo/panel-56',
  path: '/demo/panel-56',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPanel57Route = DemoPanel57RouteImport.update({
  id: '/demo/panel-57',
  path: '/demo/panel-57',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPanel58Route = DemoPanel58RouteImport.update({
  id: '/demo/panel-58',
  path: '/demo/panel-58',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPanel59Route = DemoPanel59RouteImport.update({
  id: '/demo/panel-59',
  path: '/demo/panel-59',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPanel60Route = DemoPanel60RouteImport.update({
  id: '/demo/panel-60',
  path: '/demo/panel-60',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/demo/panel-01': typeof DemoPanel01Route
  '/demo/panel-02': typeof DemoPanel02Route
  '/demo/panel-03': typeof DemoPanel03Route
  '/demo/panel-04': typeof DemoPanel04Route
  '/demo/panel-05': typeof DemoPanel05Route
  '/demo/panel-06': typeof DemoPanel06Route
  '/demo/panel-07': typeof DemoPanel07Route
  '/demo/panel-08': typeof DemoPanel08Route
  '/demo/panel-09': typeof DemoPanel09Route
  '/demo/panel-10': typeof DemoPanel10Route
  '/demo/panel-11': typeof DemoPanel11Route
  '/demo/panel-12': typeof DemoPanel12Route
  '/demo/panel-13': typeof DemoPanel13Route
  '/demo/panel-14': typeof DemoPanel14Route
  '/demo/panel-15': typeof DemoPanel15Route
  '/demo/panel-16': typeof DemoPanel16Route
  '/demo/panel-17': typeof DemoPanel17Route
  '/demo/panel-18': typeof DemoPanel18Route
  '/demo/panel-19': typeof DemoPanel19Route
  '/demo/panel-20': typeof DemoPanel20Route
  '/demo/panel-21': typeof DemoPanel21Route
  '/demo/panel-22': typeof DemoPanel22Route
  '/demo/panel-23': typeof DemoPanel23Route
  '/demo/panel-24': typeof DemoPanel24Route
  '/demo/panel-25': typeof DemoPanel25Route
  '/demo/panel-26': typeof DemoPanel26Route
  '/demo/panel-27': typeof DemoPanel27Route
  '/demo/panel-28': typeof DemoPanel28Route
  '/demo/panel-29': typeof DemoPanel29Route
  '/demo/panel-30': typeof DemoPanel30Route
  '/demo/panel-31': typeof DemoPanel31Route
  '/demo/panel-32': typeof DemoPanel32Route
  '/demo/panel-33': typeof DemoPanel33Route
  '/demo/panel-34': typeof DemoPanel34Route
  '/demo/panel-35': typeof DemoPanel35Route
  '/demo/panel-36': typeof DemoPanel36Route
  '/demo/panel-37': typeof DemoPanel37Route
  '/demo/panel-38': typeof DemoPanel38Route
  '/demo/panel-39': typeof DemoPanel39Route
  '/demo/panel-40': typeof DemoPanel40Route
  '/demo/panel-41': typeof DemoPanel41Route
  '/demo/panel-42': typeof DemoPanel42Route
  '/demo/panel-43': typeof DemoPanel43Route
  '/demo/panel-44': typeof DemoPanel44Route
  '/demo/panel-45': typeof DemoPanel45Route
  '/demo/panel-46': typeof DemoPanel46Route
  '/demo/panel-47': typeof DemoPanel47Route
  '/demo/panel-48': typeof DemoPanel48Route
  '/demo/panel-49': typeof DemoPanel49Route
  '/demo/panel-50': typeof DemoPanel50Route
  '/demo/panel-51': typeof DemoPanel51Route
  '/demo/panel-52': typeof DemoPanel52Route
  '/demo/panel-53': typeof DemoPanel53Route
  '/demo/panel-54': typeof DemoPanel54Route
  '/demo/panel-55': typeof DemoPanel55Route
  '/demo/panel-56': typeof DemoPanel56Route
  '/demo/panel-57': typeof DemoPanel57Route
  '/demo/panel-58': typeof DemoPanel58Route
  '/demo/panel-59': typeof DemoPanel59Route
  '/demo/panel-60': typeof DemoPanel60Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/demo/panel-01': typeof DemoPanel01Route
  '/demo/panel-02': typeof DemoPanel02Route
  '/demo/panel-03': typeof DemoPanel03Route
  '/demo/panel-04': typeof DemoPanel04Route
  '/demo/panel-05': typeof DemoPanel05Route
  '/demo/panel-06': typeof DemoPanel06Route
  '/demo/panel-07': typeof DemoPanel07Route
  '/demo/panel-08': typeof DemoPanel08Route
  '/demo/panel-09': typeof DemoPanel09Route
  '/demo/panel-10': typeof DemoPanel10Route
  '/demo/panel-11': typeof DemoPanel11Route
  '/demo/panel-12': typeof DemoPanel12Route
  '/demo/panel-13': typeof DemoPanel13Route
  '/demo/panel-14': typeof DemoPanel14Route
  '/demo/panel-15': typeof DemoPanel15Route
  '/demo/panel-16': typeof DemoPanel16Route
  '/demo/panel-17': typeof DemoPanel17Route
  '/demo/panel-18': typeof DemoPanel18Route
  '/demo/panel-19': typeof DemoPanel19Route
  '/demo/panel-20': typeof DemoPanel20Route
  '/demo/panel-21': typeof DemoPanel21Route
  '/demo/panel-22': typeof DemoPanel22Route
  '/demo/panel-23': typeof DemoPanel23Route
  '/demo/panel-24': typeof DemoPanel24Route
  '/demo/panel-25': typeof DemoPanel25Route
  '/demo/panel-26': typeof DemoPanel26Route
  '/demo/panel-27': typeof DemoPanel27Route
  '/demo/panel-28': typeof DemoPanel28Route
  '/demo/panel-29': typeof DemoPanel29Route
  '/demo/panel-30': typeof DemoPanel30Route
  '/demo/panel-31': typeof DemoPanel31Route
  '/demo/panel-32': typeof DemoPanel32Route
  '/demo/panel-33': typeof DemoPanel33Route
  '/demo/panel-34': typeof DemoPanel34Route
  '/demo/panel-35': typeof DemoPanel35Route
  '/demo/panel-36': typeof DemoPanel36Route
  '/demo/panel-37': typeof DemoPanel37Route
  '/demo/panel-38': typeof DemoPanel38Route
  '/demo/panel-39': typeof DemoPanel39Route
  '/demo/panel-40': typeof DemoPanel40Route
  '/demo/panel-41': typeof DemoPanel41Route
  '/demo/panel-42': typeof DemoPanel42Route
  '/demo/panel-43': typeof DemoPanel43Route
  '/demo/panel-44': typeof DemoPanel44Route
  '/demo/panel-45': typeof DemoPanel45Route
  '/demo/panel-46': typeof DemoPanel46Route
  '/demo/panel-47': typeof DemoPanel47Route
  '/demo/panel-48': typeof DemoPanel48Route
  '/demo/panel-49': typeof DemoPanel49Route
  '/demo/panel-50': typeof DemoPanel50Route
  '/demo/panel-51': typeof DemoPanel51Route
  '/demo/panel-52': typeof DemoPanel52Route
  '/demo/panel-53': typeof DemoPanel53Route
  '/demo/panel-54': typeof DemoPanel54Route
  '/demo/panel-55': typeof DemoPanel55Route
  '/demo/panel-56': typeof DemoPanel56Route
  '/demo/panel-57': typeof DemoPanel57Route
  '/demo/panel-58': typeof DemoPanel58Route
  '/demo/panel-59': typeof DemoPanel59Route
  '/demo/panel-60': typeof DemoPanel60Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/demo/panel-01': typeof DemoPanel01Route
  '/demo/panel-02': typeof DemoPanel02Route
  '/demo/panel-03': typeof DemoPanel03Route
  '/demo/panel-04': typeof DemoPanel04Route
  '/demo/panel-05': typeof DemoPanel05Route
  '/demo/panel-06': typeof DemoPanel06Route
  '/demo/panel-07': typeof DemoPanel07Route
  '/demo/panel-08': typeof DemoPanel08Route
  '/demo/panel-09': typeof DemoPanel09Route
  '/demo/panel-10': typeof DemoPanel10Route
  '/demo/panel-11': typeof DemoPanel11Route
  '/demo/panel-12': typeof DemoPanel12Route
  '/demo/panel-13': typeof DemoPanel13Route
  '/demo/panel-14': typeof DemoPanel14Route
  '/demo/panel-15': typeof DemoPanel15Route
  '/demo/panel-16': typeof DemoPanel16Route
  '/demo/panel-17': typeof DemoPanel17Route
  '/demo/panel-18': typeof DemoPanel18Route
  '/demo/panel-19': typeof DemoPanel19Route
  '/demo/panel-20': typeof DemoPanel20Route
  '/demo/panel-21': typeof DemoPanel21Route
  '/demo/panel-22': typeof DemoPanel22Route
  '/demo/panel-23': typeof DemoPanel23Route
  '/demo/panel-24': typeof DemoPanel24Route
  '/demo/panel-25': typeof DemoPanel25Route
  '/demo/panel-26': typeof DemoPanel26Route
  '/demo/panel-27': typeof DemoPanel27Route
  '/demo/panel-28': typeof DemoPanel28Route
  '/demo/panel-29': typeof DemoPanel29Route
  '/demo/panel-30': typeof DemoPanel30Route
  '/demo/panel-31': typeof DemoPanel31Route
  '/demo/panel-32': typeof DemoPanel32Route
  '/demo/panel-33': typeof DemoPanel33Route
  '/demo/panel-34': typeof DemoPanel34Route
  '/demo/panel-35': typeof DemoPanel35Route
  '/demo/panel-36': typeof DemoPanel36Route
  '/demo/panel-37': typeof DemoPanel37Route
  '/demo/panel-38': typeof DemoPanel38Route
  '/demo/panel-39': typeof DemoPanel39Route
  '/demo/panel-40': typeof DemoPanel40Route
  '/demo/panel-41': typeof DemoPanel41Route
  '/demo/panel-42': typeof DemoPanel42Route
  '/demo/panel-43': typeof DemoPanel43Route
  '/demo/panel-44': typeof DemoPanel44Route
  '/demo/panel-45': typeof DemoPanel45Route
  '/demo/panel-46': typeof DemoPanel46Route
  '/demo/panel-47': typeof DemoPanel47Route
  '/demo/panel-48': typeof DemoPanel48Route
  '/demo/panel-49': typeof DemoPanel49Route
  '/demo/panel-50': typeof DemoPanel50Route
  '/demo/panel-51': typeof DemoPanel51Route
  '/demo/panel-52': typeof DemoPanel52Route
  '/demo/panel-53': typeof DemoPanel53Route
  '/demo/panel-54': typeof DemoPanel54Route
  '/demo/panel-55': typeof DemoPanel55Route
  '/demo/panel-56': typeof DemoPanel56Route
  '/demo/panel-57': typeof DemoPanel57Route
  '/demo/panel-58': typeof DemoPanel58Route
  '/demo/panel-59': typeof DemoPanel59Route
  '/demo/panel-60': typeof DemoPanel60Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/demo/panel-01'
    | '/demo/panel-02'
    | '/demo/panel-03'
    | '/demo/panel-04'
    | '/demo/panel-05'
    | '/demo/panel-06'
    | '/demo/panel-07'
    | '/demo/panel-08'
    | '/demo/panel-09'
    | '/demo/panel-10'
    | '/demo/panel-11'
    | '/demo/panel-12'
    | '/demo/panel-13'
    | '/demo/panel-14'
    | '/demo/panel-15'
    | '/demo/panel-16'
    | '/demo/panel-17'
    | '/demo/panel-18'
    | '/demo/panel-19'
    | '/demo/panel-20'
    | '/demo/panel-21'
    | '/demo/panel-22'
    | '/demo/panel-23'
    | '/demo/panel-24'
    | '/demo/panel-25'
    | '/demo/panel-26'
    | '/demo/panel-27'
    | '/demo/panel-28'
    | '/demo/panel-29'
    | '/demo/panel-30'
    | '/demo/panel-31'
    | '/demo/panel-32'
    | '/demo/panel-33'
    | '/demo/panel-34'
    | '/demo/panel-35'
    | '/demo/panel-36'
    | '/demo/panel-37'
    | '/demo/panel-38'
    | '/demo/panel-39'
    | '/demo/panel-40'
    | '/demo/panel-41'
    | '/demo/panel-42'
    | '/demo/panel-43'
    | '/demo/panel-44'
    | '/demo/panel-45'
    | '/demo/panel-46'
    | '/demo/panel-47'
    | '/demo/panel-48'
    | '/demo/panel-49'
    | '/demo/panel-50'
    | '/demo/panel-51'
    | '/demo/panel-52'
    | '/demo/panel-53'
    | '/demo/panel-54'
    | '/demo/panel-55'
    | '/demo/panel-56'
    | '/demo/panel-57'
    | '/demo/panel-58'
    | '/demo/panel-59'
    | '/demo/panel-60'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/demo/panel-01'
    | '/demo/panel-02'
    | '/demo/panel-03'
    | '/demo/panel-04'
    | '/demo/panel-05'
    | '/demo/panel-06'
    | '/demo/panel-07'
    | '/demo/panel-08'
    | '/demo/panel-09'
    | '/demo/panel-10'
    | '/demo/panel-11'
    | '/demo/panel-12'
    | '/demo/panel-13'
    | '/demo/panel-14'
    | '/demo/panel-15'
    | '/demo/panel-16'
    | '/demo/panel-17'
    | '/demo/panel-18'
    | '/demo/panel-19'
    | '/demo/panel-20'
    | '/demo/panel-21'
    | '/demo/panel-22'
    | '/demo/panel-23'
    | '/demo/panel-24'
    | '/demo/panel-25'
    | '/demo/panel-26'
    | '/demo/panel-27'
    | '/demo/panel-28'
    | '/demo/panel-29'
    | '/demo/panel-30'
    | '/demo/panel-31'
    | '/demo/panel-32'
    | '/demo/panel-33'
    | '/demo/panel-34'
    | '/demo/panel-35'
    | '/demo/panel-36'
    | '/demo/panel-37'
    | '/demo/panel-38'
    | '/demo/panel-39'
    | '/demo/panel-40'
    | '/demo/panel-41'
    | '/demo/panel-42'
    | '/demo/panel-43'
    | '/demo/panel-44'
    | '/demo/panel-45'
    | '/demo/panel-46'
    | '/demo/panel-47'
    | '/demo/panel-48'
    | '/demo/panel-49'
    | '/demo/panel-50'
    | '/demo/panel-51'
    | '/demo/panel-52'
    | '/demo/panel-53'
    | '/demo/panel-54'
    | '/demo/panel-55'
    | '/demo/panel-56'
    | '/demo/panel-57'
    | '/demo/panel-58'
    | '/demo/panel-59'
    | '/demo/panel-60'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/demo/panel-01'
    | '/demo/panel-02'
    | '/demo/panel-03'
    | '/demo/panel-04'
    | '/demo/panel-05'
    | '/demo/panel-06'
    | '/demo/panel-07'
    | '/demo/panel-08'
    | '/demo/panel-09'
    | '/demo/panel-10'
    | '/demo/panel-11'
    | '/demo/panel-12'
    | '/demo/panel-13'
    | '/demo/panel-14'
    | '/demo/panel-15'
    | '/demo/panel-16'
    | '/demo/panel-17'
    | '/demo/panel-18'
    | '/demo/panel-19'
    | '/demo/panel-20'
    | '/demo/panel-21'
    | '/demo/panel-22'
    | '/demo/panel-23'
    | '/demo/panel-24'
    | '/demo/panel-25'
    | '/demo/panel-26'
    | '/demo/panel-27'
    | '/demo/panel-28'
    | '/demo/panel-29'
    | '/demo/panel-30'
    | '/demo/panel-31'
    | '/demo/panel-32'
    | '/demo/panel-33'
    | '/demo/panel-34'
    | '/demo/panel-35'
    | '/demo/panel-36'
    | '/demo/panel-37'
    | '/demo/panel-38'
    | '/demo/panel-39'
    | '/demo/panel-40'
    | '/demo/panel-41'
    | '/demo/panel-42'
    | '/demo/panel-43'
    | '/demo/panel-44'
    | '/demo/panel-45'
    | '/demo/panel-46'
    | '/demo/panel-47'
    | '/demo/panel-48'
    | '/demo/panel-49'
    | '/demo/panel-50'
    | '/demo/panel-51'
    | '/demo/panel-52'
    | '/demo/panel-53'
    | '/demo/panel-54'
    | '/demo/panel-55'
    | '/demo/panel-56'
    | '/demo/panel-57'
    | '/demo/panel-58'
    | '/demo/panel-59'
    | '/demo/panel-60'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DemoPanel01Route: typeof DemoPanel01Route
  DemoPanel02Route: typeof DemoPanel02Route
  DemoPanel03Route: typeof DemoPanel03Route
  DemoPanel04Route: typeof DemoPanel04Route
  DemoPanel05Route: typeof DemoPanel05Route
  DemoPanel06Route: typeof DemoPanel06Route
  DemoPanel07Route: typeof DemoPanel07Route
  DemoPanel08Route: typeof DemoPanel08Route
  DemoPanel09Route: typeof DemoPanel09Route
  DemoPanel10Route: typeof DemoPanel10Route
  DemoPanel11Route: typeof DemoPanel11Route
  DemoPanel12Route: typeof DemoPanel12Route
  DemoPanel13Route: typeof DemoPanel13Route
  DemoPanel14Route: typeof DemoPanel14Route
  DemoPanel15Route: typeof DemoPanel15Route
  DemoPanel16Route: typeof DemoPanel16Route
  DemoPanel17Route: typeof DemoPanel17Route
  DemoPanel18Route: typeof DemoPanel18Route
  DemoPanel19Route: typeof DemoPanel19Route
  DemoPanel20Route: typeof DemoPanel20Route
  DemoPanel21Route: typeof DemoPanel21Route
  DemoPanel22Route: typeof DemoPanel22Route
  DemoPanel23Route: typeof DemoPanel23Route
  DemoPanel24Route: typeof DemoPanel24Route
  DemoPanel25Route: typeof DemoPanel25Route
  DemoPanel26Route: typeof DemoPanel26Route
  DemoPanel27Route: typeof DemoPanel27Route
  DemoPanel28Route: typeof DemoPanel28Route
  DemoPanel29Route: typeof DemoPanel29Route
  DemoPanel30Route: typeof DemoPanel30Route
  DemoPanel31Route: typeof DemoPanel31Route
  DemoPanel32Route: typeof DemoPanel32Route
  DemoPanel33Route: typeof DemoPanel33Route
  DemoPanel34Route: typeof DemoPanel34Route
  DemoPanel35Route: typeof DemoPanel35Route
  DemoPanel36Route: typeof DemoPanel36Route
  DemoPanel37Route: typeof DemoPanel37Route
  DemoPanel38Route: typeof DemoPanel38Route
  DemoPanel39Route: typeof DemoPanel39Route
  DemoPanel40Route: typeof DemoPanel40Route
  DemoPanel41Route: typeof DemoPanel41Route
  DemoPanel42Route: typeof DemoPanel42Route
  DemoPanel43Route: typeof DemoPanel43Route
  DemoPanel44Route: typeof DemoPanel44Route
  DemoPanel45Route: typeof DemoPanel45Route
  DemoPanel46Route: typeof DemoPanel46Route
  DemoPanel47Route: typeof DemoPanel47Route
  DemoPanel48Route: typeof DemoPanel48Route
  DemoPanel49Route: typeof DemoPanel49Route
  DemoPanel50Route: typeof DemoPanel50Route
  DemoPanel51Route: typeof DemoPanel51Route
  DemoPanel52Route: typeof DemoPanel52Route
  DemoPanel53Route: typeof DemoPanel53Route
  DemoPanel54Route: typeof DemoPanel54Route
  DemoPanel55Route: typeof DemoPanel55Route
  DemoPanel56Route: typeof DemoPanel56Route
  DemoPanel57Route: typeof DemoPanel57Route
  DemoPanel58Route: typeof DemoPanel58Route
  DemoPanel59Route: typeof DemoPanel59Route
  DemoPanel60Route: typeof DemoPanel60Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/panel-01': {
      id: '/demo/panel-01'
      path: '/demo/panel-01'
      fullPath: '/demo/panel-01'
      preLoaderRoute: typeof DemoPanel01RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/panel-02': {
      id: '/demo/panel-02'
      path: '/demo/panel-02'
      fullPath: '/demo/panel-02'
      preLoaderRoute: typeof DemoPanel02RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/panel-03': {
      id: '/demo/panel-03'
      path: '/demo/panel-03'
      fullPath: '/demo/panel-03'
      preLoaderRoute: typeof DemoPanel03RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/panel-04': {
      id: '/demo/panel-04'
      path: '/demo/panel-04'
      fullPath: '/demo/panel-04'
      preLoaderRoute: typeof DemoPanel04RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/panel-05': {
      id: '/demo/panel-05'
      path: '/demo/panel-05'
      fullPath: '/demo/panel-05'
      preLoaderRoute: typeof DemoPanel05RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/panel-06': {
      id: '/demo/panel-06'
      path: '/demo/panel-06'
      fullPath: '/demo/panel-06'
      preLoaderRoute: typeof DemoPanel06RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/panel-07': {
      id: '/demo/panel-07'
      path: '/demo/panel-07'
      fullPath: '/demo/panel-07'
      preLoaderRoute: typeof DemoPanel07RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/panel-08': {
      id: '/demo/panel-08'
      path: '/demo/panel-08'
      fullPath: '/demo/panel-08'
      preLoaderRoute: typeof DemoPanel08RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/panel-09': {
      id: '/demo/panel-09'
      path: '/demo/panel-09'
      fullPath: '/demo/panel-09'
      preLoaderRoute: typeof DemoPanel09RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/panel-10': {
      id: '/demo/panel-10'
      path: '/demo/panel-10'
      fullPath: '/demo/panel-10'
      preLoaderRoute: typeof DemoPanel10RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/panel-11': {
      id: '/demo/panel-11'
      path: '/demo/panel-11'
      fullPath: '/demo/panel-11'
      preLoaderRoute: typeof DemoPanel11RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/panel-12': {
      id: '/demo/panel-12'
      path: '/demo/panel-12'
      fullPath: '/demo/panel-12'
      preLoaderRoute: typeof DemoPanel12RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/panel-13': {
      id: '/demo/panel-13'
      path: '/demo/panel-13'
      fullPath: '/demo/panel-13'
      preLoaderRoute: typeof DemoPanel13RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/panel-14': {
      id: '/demo/panel-14'
      path: '/demo/panel-14'
      fullPath: '/demo/panel-14'
      preLoaderRoute: typeof DemoPanel14RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/panel-15': {
      id: '/demo/panel-15'
      path: '/demo/panel-15'
      fullPath: '/demo/panel-15'
      preLoaderRoute: typeof DemoPanel15RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/panel-16': {
      id: '/demo/panel-16'
      path: '/demo/panel-16'
      fullPath: '/demo/panel-16'
      preLoaderRoute: typeof DemoPanel16RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/panel-17': {
      id: '/demo/panel-17'
      path: '/demo/panel-17'
      fullPath: '/demo/panel-17'
      preLoaderRoute: typeof DemoPanel17RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/panel-18': {
      id: '/demo/panel-18'
      path: '/demo/panel-18'
      fullPath: '/demo/panel-18'
      preLoaderRoute: typeof DemoPanel18RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/panel-19': {
      id: '/demo/panel-19'
      path: '/demo/panel-19'
      fullPath: '/demo/panel-19'
      preLoaderRoute: typeof DemoPanel19RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/panel-20': {
      id: '/demo/panel-20'
      path: '/demo/panel-20'
      fullPath: '/demo/panel-20'
      preLoaderRoute: typeof DemoPanel20RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/panel-21': {
      id: '/demo/panel-21'
      path: '/demo/panel-21'
      fullPath: '/demo/panel-21'
      preLoaderRoute: typeof DemoPanel21RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/panel-22': {
      id: '/demo/panel-22'
      path: '/demo/panel-22'
      fullPath: '/demo/panel-22'
      preLoaderRoute: typeof DemoPanel22RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/panel-23': {
      id: '/demo/panel-23'
      path: '/demo/panel-23'
      fullPath: '/demo/panel-23'
      preLoaderRoute: typeof DemoPanel23RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/panel-24': {
      id: '/demo/panel-24'
      path: '/demo/panel-24'
      fullPath: '/demo/panel-24'
      preLoaderRoute: typeof DemoPanel24RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/panel-25': {
      id: '/demo/panel-25'
      path: '/demo/panel-25'
      fullPath: '/demo/panel-25'
      preLoaderRoute: typeof DemoPanel25RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/panel-26': {
      id: '/demo/panel-26'
      path: '/demo/panel-26'
      fullPath: '/demo/panel-26'
      preLoaderRoute: typeof DemoPanel26RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/panel-27': {
      id: '/demo/panel-27'
      path: '/demo/panel-27'
      fullPath: '/demo/panel-27'
      preLoaderRoute: typeof DemoPanel27RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/panel-28': {
      id: '/demo/panel-28'
      path: '/demo/panel-28'
      fullPath: '/demo/panel-28'
      preLoaderRoute: typeof DemoPanel28RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/panel-29': {
      id: '/demo/panel-29'
      path: '/demo/panel-29'
      fullPath: '/demo/panel-29'
      preLoaderRoute: typeof DemoPanel29RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/panel-30': {
      id: '/demo/panel-30'
      path: '/demo/panel-30'
      fullPath: '/demo/panel-30'
      preLoaderRoute: typeof DemoPanel30RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/panel-31': {
      id: '/demo/panel-31'
      path: '/demo/panel-31'
      fullPath: '/demo/panel-31'
      preLoaderRoute: typeof DemoPanel31RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/panel-32': {
      id: '/demo/panel-32'
      path: '/demo/panel-32'
      fullPath: '/demo/panel-32'
      preLoaderRoute: typeof DemoPanel32RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/panel-33': {
      id: '/demo/panel-33'
      path: '/demo/panel-33'
      fullPath: '/demo/panel-33'
      preLoaderRoute: typeof DemoPanel33RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/panel-34': {
      id: '/demo/panel-34'
      path: '/demo/panel-34'
      fullPath: '/demo/panel-34'
      preLoaderRoute: typeof DemoPanel34RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/panel-35': {
      id: '/demo/panel-35'
      path: '/demo/panel-35'
      fullPath: '/demo/panel-35'
      preLoaderRoute: typeof DemoPanel35RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/panel-36': {
      id: '/demo/panel-36'
      path: '/demo/panel-36'
      fullPath: '/demo/panel-36'
      preLoaderRoute: typeof DemoPanel36RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/panel-37': {
      id: '/demo/panel-37'
      path: '/demo/panel-37'
      fullPath: '/demo/panel-37'
      preLoaderRoute: typeof DemoPanel37RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/panel-38': {
      id: '/demo/panel-38'
      path: '/demo/panel-38'
      fullPath: '/demo/panel-38'
      preLoaderRoute: typeof DemoPanel38RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/panel-39': {
      id: '/demo/panel-39'
      path: '/demo/panel-39'
      fullPath: '/demo/panel-39'
      preLoaderRoute: typeof DemoPanel39RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/panel-40': {
      id: '/demo/panel-40'
      path: '/demo/panel-40'
      fullPath: '/demo/panel-40'
      preLoaderRoute: typeof DemoPanel40RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/panel-41': {
      id: '/demo/panel-41'
      path: '/demo/panel-41'
      fullPath: '/demo/panel-41'
      preLoaderRoute: typeof DemoPanel41RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/panel-42': {
      id: '/demo/panel-42'
      path: '/demo/panel-42'
      fullPath: '/demo/panel-42'
      preLoaderRoute: typeof DemoPanel42RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/panel-43': {
      id: '/demo/panel-43'
      path: '/demo/panel-43'
      fullPath: '/demo/panel-43'
      preLoaderRoute: typeof DemoPanel43RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/panel-44': {
      id: '/demo/panel-44'
      path: '/demo/panel-44'
      fullPath: '/demo/panel-44'
      preLoaderRoute: typeof DemoPanel44RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/panel-45': {
      id: '/demo/panel-45'
      path: '/demo/panel-45'
      fullPath: '/demo/panel-45'
      preLoaderRoute: typeof DemoPanel45RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/panel-46': {
      id: '/demo/panel-46'
      path: '/demo/panel-46'
      fullPath: '/demo/panel-46'
      preLoaderRoute: typeof DemoPanel46RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/panel-47': {
      id: '/demo/panel-47'
      path: '/demo/panel-47'
      fullPath: '/demo/panel-47'
      preLoaderRoute: typeof DemoPanel47RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/panel-48': {
      id: '/demo/panel-48'
      path: '/demo/panel-48'
      fullPath: '/demo/panel-48'
      preLoaderRoute: typeof DemoPanel48RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/panel-49': {
      id: '/demo/panel-49'
      path: '/demo/panel-49'
      fullPath: '/demo/panel-49'
      preLoaderRoute: typeof DemoPanel49RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/panel-50': {
      id: '/demo/panel-50'
      path: '/demo/panel-50'
      fullPath: '/demo/panel-50'
      preLoaderRoute: typeof DemoPanel50RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/panel-51': {
      id: '/demo/panel-51'
      path: '/demo/panel-51'
      fullPath: '/demo/panel-51'
      preLoaderRoute: typeof DemoPanel51RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/panel-52': {
      id: '/demo/panel-52'
      path: '/demo/panel-52'
      fullPath: '/demo/panel-52'
      preLoaderRoute: typeof DemoPanel52RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/panel-53': {
      id: '/demo/panel-53'
      path: '/demo/panel-53'
      fullPath: '/demo/panel-53'
      preLoaderRoute: typeof DemoPanel53RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/panel-54': {
      id: '/demo/panel-54'
      path: '/demo/panel-54'
      fullPath: '/demo/panel-54'
      preLoaderRoute: typeof DemoPanel54RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/panel-55': {
      id: '/demo/panel-55'
      path: '/demo/panel-55'
      fullPath: '/demo/panel-55'
      preLoaderRoute: typeof DemoPanel55RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/panel-56': {
      id: '/demo/panel-56'
      path: '/demo/panel-56'
      fullPath: '/demo/panel-56'
      preLoaderRoute: typeof DemoPanel56RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/panel-57': {
      id: '/demo/panel-57'
      path: '/demo/panel-57'
      fullPath: '/demo/panel-57'
      preLoaderRoute: typeof DemoPanel57RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/panel-58': {
      id: '/demo/panel-58'
      path: '/demo/panel-58'
      fullPath: '/demo/panel-58'
      preLoaderRoute: typeof DemoPanel58RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/panel-59': {
      id: '/demo/panel-59'
      path: '/demo/panel-59'
      fullPath: '/demo/panel-59'
      preLoaderRoute: typeof DemoPanel59RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/panel-60': {
      id: '/demo/panel-60'
      path: '/demo/panel-60'
      fullPath: '/demo/panel-60'
      preLoaderRoute: typeof DemoPanel60RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DemoPanel01Route: DemoPanel01Route,
  DemoPanel02Route: DemoPanel02Route,
  DemoPanel03Route: DemoPanel03Route,
  DemoPanel04Route: DemoPanel04Route,
  DemoPanel05Route: DemoPanel05Route,
  DemoPanel06Route: DemoPanel06Route,
  DemoPanel07Route: DemoPanel07Route,
  DemoPanel08Route: DemoPanel08Route,
  DemoPanel09Route: DemoPanel09Route,
  DemoPanel10Route: DemoPanel10Route,
  DemoPanel11Route: DemoPanel11Route,
  DemoPanel12Route: DemoPanel12Route,
  DemoPanel13Route: DemoPanel13Route,
  DemoPanel14Route: DemoPanel14Route,
  DemoPanel15Route: DemoPanel15Route,
  DemoPanel16Route: DemoPanel16Route,
  DemoPanel17Route: DemoPanel17Route,
  DemoPanel18Route: DemoPanel18Route,
  DemoPanel19Route: DemoPanel19Route,
  DemoPanel20Route: DemoPanel20Route,
  DemoPanel21Route: DemoPanel21Route,
  DemoPanel22Route: DemoPanel22Route,
  DemoPanel23Route: DemoPanel23Route,
  DemoPanel24Route: DemoPanel24Route,
  DemoPanel25Route: DemoPanel25Route,
  DemoPanel26Route: DemoPanel26Route,
  DemoPanel27Route: DemoPanel27Route,
  DemoPanel28Route: DemoPanel28Route,
  DemoPanel29Route: DemoPanel29Route,
  DemoPanel30Route: DemoPanel30Route,
  DemoPanel31Route: DemoPanel31Route,
  DemoPanel32Route: DemoPanel32Route,
  DemoPanel33Route: DemoPanel33Route,
  DemoPanel34Route: DemoPanel34Route,
  DemoPanel35Route: DemoPanel35Route,
  DemoPanel36Route: DemoPanel36Route,
  DemoPanel37Route: DemoPanel37Route,
  DemoPanel38Route: DemoPanel38Route,
  DemoPanel39Route: DemoPanel39Route,
  DemoPanel40Route: DemoPanel40Route,
  DemoPanel41Route: DemoPanel41Route,
  DemoPanel42Route: DemoPanel42Route,
  DemoPanel43Route: DemoPanel43Route,
  DemoPanel44Route: DemoPanel44Route,
  DemoPanel45Route: DemoPanel45Route,
  DemoPanel46Route: DemoPanel46Route,
  DemoPanel47Route: DemoPanel47Route,
  DemoPanel48Route: DemoPanel48Route,
  DemoPanel49Route: DemoPanel49Route,
  DemoPanel50Route: DemoPanel50Route,
  DemoPanel51Route: DemoPanel51Route,
  DemoPanel52Route: DemoPanel52Route,
  DemoPanel53Route: DemoPanel53Route,
  DemoPanel54Route: DemoPanel54Route,
  DemoPanel55Route: DemoPanel55Route,
  DemoPanel56Route: DemoPanel56Route,
  DemoPanel57Route: DemoPanel57Route,
  DemoPanel58Route: DemoPanel58Route,
  DemoPanel59Route: DemoPanel59Route,
  DemoPanel60Route: DemoPanel60Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
